import { ArrowRight, CheckCircle2, MapPin, PackageCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { apiRequest } from '../api/client.js'

export default function OrderSuccessPage() {
  const { id } = useParams()
  const [order, setOrder] = useState(null)
  useEffect(() => { apiRequest(`/orders/${id}`).then(({ order: fetched }) => setOrder(fetched)).catch(() => {}) }, [id])
  return <section className="px-4 py-20"><div className="mx-auto max-w-3xl text-center"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-[#e8f2e5]"><CheckCircle2 className="h-12 w-12 text-[#3d7949]" strokeWidth={1.4} /></div><p className="mt-8 text-[10px] font-black uppercase tracking-[.25em] text-[#a1711b]">Order confirmed</p><h1 className="mt-3 font-display text-5xl text-[#183222]">Thank you for choosing wellness.</h1><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-[#6f7b73]">Your order has been placed successfully. Delivery updates will use the verified details supplied at checkout.</p><p className="mt-6 text-xs font-bold uppercase tracking-wider text-[#849088]">Order #{id.slice(-8).toUpperCase()}</p>{order && <div className="mt-10 grid gap-4 text-left sm:grid-cols-2"><div className="rounded-2xl border border-[#dfe5da] bg-white p-6"><PackageCheck className="h-5 w-5 text-[#9d711d]" /><p className="mt-4 text-[9px] font-black uppercase tracking-wider text-[#879189]">Order summary</p><p className="mt-2 text-sm leading-6 text-[#4f5e54]">{order.items.map((item) => `${item.name} × ${item.quantity}`).join(', ')}</p><p className="mt-3 font-black text-[#193824]">₹{order.totalPrice.toLocaleString('en-IN')} · {order.paymentMethod}</p></div><div className="rounded-2xl border border-[#dfe5da] bg-white p-6"><MapPin className="h-5 w-5 text-[#9d711d]" /><p className="mt-4 text-[9px] font-black uppercase tracking-wider text-[#879189]">Delivery information</p><p className="mt-2 text-sm leading-6 text-[#4f5e54]">{order.shippingAddress.fullName}<br />{order.shippingAddress.addressLine}, {order.shippingAddress.city}<br />{order.shippingAddress.state} {order.shippingAddress.postalCode}</p></div></div>}<div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to={`/orders/${id}`} className="rounded-full bg-[#123b2a] px-8 py-4 text-[10px] font-black uppercase tracking-wider text-white">Track your order</Link><Link to="/shop" className="inline-flex items-center justify-center gap-2 rounded-full border border-[#b58428] px-8 py-4 text-[10px] font-black uppercase tracking-wider text-[#946516]">Continue shopping <ArrowRight className="h-4 w-4" /></Link></div></div></section>
}
