import { AlertCircle, FileText } from 'lucide-react'

const policies = {
  shipping: { eyebrow: 'Shipping & delivery', title: 'From our care to your doorstep.', intro: 'This pre-launch policy structure covers serviceability, timelines, charges and delivery support. Final operational values must be approved before orders go live.', sections: [['Delivery areas', 'Orders will be accepted only for serviceable Indian PIN codes shown at checkout. Confirm excluded regions and courier coverage before launch.'], ['Estimated delivery time', 'Display order processing and transit estimates at checkout after courier agreements are finalised. Delays may occur due to weather, public holidays or remote-area serviceability.'], ['Shipping charges', 'The current demo checkout applies ₹99 shipping and free delivery from ₹999. Confirm these commercial rules before launch.'], ['Order tracking', 'A dispatch and tracking reference will be shared through the verified email or mobile number attached to the order.'], ['Delivery issues', 'Customers should report delays, missing parcels or an incorrect delivery status using the contact form and order number.'], ['Damaged package', 'Photograph the outer package, shipping label and product immediately. Keep all packaging until the support team completes its review.']] },
  returns: { eyebrow: 'Returns & refunds', title: 'A fair, safety-first process.', intro: 'Wellness products need careful return rules. The final policy must reflect actual business operations and applicable Indian consumer and ecommerce requirements.', sections: [['Return eligibility', 'State the exact return request window and require proof of purchase. Products should remain unused, sealed and in original packaging unless the issue is damage or an incorrect item.'], ['Opened products', 'Opened or used ingestible products are generally restricted for health and safety reasons. Publish the final exception rules after legal review.'], ['Damaged or incorrect order', 'Ask customers to report the issue promptly with order number, photographs and an unboxing record where available.'], ['Refund processing', 'Approved refunds should return to the original payment method within the final published banking timeline. COD refund handling must also be defined.'], ['Cancellations', 'State when cancellation is possible before packing or dispatch. Dispatched orders follow the applicable return rules.'], ['Policy review', 'This page is a pre-launch template and requires approval against the actual business policy before accepting orders.']] },
  privacy: { eyebrow: 'Privacy policy', title: 'Your information, handled with care.', intro: 'This summary explains the intended data flow. It must be completed with the legal business identity, processors, retention periods and grievance contact before launch.', sections: [['Information collected', 'Account details, name, email, mobile number, delivery address, order records and messages submitted through the contact form.'], ['Why it is used', 'To create accounts, authenticate sessions, fulfil orders, provide support, prevent abuse and improve store operations.'], ['Payment information', 'The demo supports COD and payment-pending online orders. A live payment provider should process sensitive card or UPI credentials; the store should not store full payment credentials.'], ['Cookies and local storage', 'The storefront uses local storage for the cart and JWT session. Add consent controls for non-essential analytics or marketing tools before enabling them.'], ['Marketing communications', 'Send promotional communications only with appropriate consent and provide a clear opt-out.'], ['Protection and contact', 'Use HTTPS, access controls, limited retention and security monitoring. Publish the official privacy or grievance contact after verification.']] },
  terms: { eyebrow: 'Terms & conditions', title: 'Clear rules for a trusted store.', intro: 'These pre-launch terms outline the required topics. They must be reviewed with the final business identity, policies, product status and applicable law before publication.', sections: [['Website use', 'Users must provide accurate information, use the site lawfully and not interfere with its security or operation.'], ['Accounts', 'Customers are responsible for protecting login credentials and informing support of suspected unauthorised access.'], ['Products and information', 'Final products, labels, ingredients, classification, claims, images, prices and availability may be published only after verification. Website information is not medical advice.'], ['Orders and payments', 'An order is accepted only after confirmation. Pricing errors, stock issues, payment failure, suspected fraud or serviceability problems may require cancellation and refund.'], ['Intellectual property', 'Brand assets, copy and original site materials remain protected by applicable intellectual-property rights.'], ['Liability and governing terms', 'Add legally reviewed limitations, applicable Indian law, jurisdiction, grievance contact and consumer rights without excluding rights that cannot lawfully be limited.']] },
}

export default function PolicyPage({ type }) {
  const policy = policies[type] || policies.shipping
  return <div><section className="bg-[#0b271b] px-4 py-20 text-center text-white"><FileText className="mx-auto h-8 w-8 text-[#d9b45f]" strokeWidth={1.3} /><p className="mt-6 text-[10px] font-black uppercase tracking-[.25em] text-[#dfb75e]">{policy.eyebrow}</p><h1 className="mx-auto mt-4 max-w-4xl font-display text-6xl leading-tight text-[#fff6df]">{policy.title}</h1><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-white/58">{policy.intro}</p></section><section className="px-4 py-16 sm:px-6"><div className="mx-auto max-w-5xl"><div className="mb-8 flex gap-3 rounded-2xl border border-[#e4cb85] bg-[#fff7df] p-5 text-xs leading-6 text-[#715923]"><AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-[#a8761b]" /><p><strong>Pre-launch review required:</strong> replace all operational items with the actual approved business policy and official contact details before accepting live orders.</p></div><div className="grid gap-4 md:grid-cols-2">{policy.sections.map(([title, text], index) => <article key={title} className="rounded-[1.75rem] border border-[#dfe5da] bg-white p-7"><span className="font-display text-3xl text-[#c3973d]">0{index + 1}</span><h2 className="mt-5 font-display text-2xl text-[#193824]">{title}</h2><p className="mt-3 text-sm leading-7 text-[#69766d]">{text}</p></article>)}</div></div></section></div>
}
