// Clean 4 products catalog: Sugar Shield, Endless, Lean Shape, Vital Infinity
export const initialProducts = [
  {
    "slug": "sugar-shield-blood-sugar-support",
    "name": "SUGAR SHIELD",
    "subtitle": "Blood Sugar Support Capsules",
    "category": "Metabolic Wellness",
    "price": 1499,
    "mrp": 1499,
    "countInStock": 25,
    "rating": 4.9,
    "numReviews": 14,
    "badge": "60 CAPSULES",
    "theme": "emerald",
    "featured": true,
    "shortDescription": "A planned botanical capsule formula for responsible, everyday metabolic wellness support.",
    "description": "Sugar Shield brings together traditional Ayurvedic herbs including Jamun, Methi, Neem, and Amla in a convenient daily capsule format to support a balanced metabolic wellness routine alongside mindful nutrition and healthy daily habits.",
    "ingredients": [
      "Jamun Extract",
      "Methi / Fenugreek Extract",
      "Neem Leaf Extract",
      "Amla / Indian Gooseberry",
      "Gudmar Extract",
      "Karela / Bitter Gourd Extract",
      "Vijaysar Extract",
      "Cinnamon Extract"
    ],
    "benefits": [
      "Supports healthy blood sugar balance*",
      "Supports daily energy & metabolic rhythm*",
      "Contains potent Ayurvedic botanical extracts*",
      "Supports natural antioxidant defenses*",
      "Convenient vegetarian capsule format*"
    ],
    "size": "60 capsules",
    "form": "Capsules",
    "classification": "Ayurvedic Proprietary Medicine",
    "vegetarian": "100% Vegetarian",
    "storage": "Store in a cool, dry and dark place. Keep away from direct sunlight.",
    "usage": "Take 1-2 capsules twice daily, 30 minutes before meals with lukewarm water, or as directed by a healthcare professional.",
    "disclaimer": "This product is not intended to diagnose, treat, cure or prevent any disease. Do not exceed the recommended dosage. Keep out of reach of children. Consult a qualified healthcare professional if you are pregnant, breastfeeding, have a medical condition, or take medication.",
    "images": [
      "/images/home/Suger sheid.png"
    ],
    "imageStatus": "Concept",
    "availableForPurchase": true,
    "sortOrder": 0,
    "cardImage": "/images/home/Suger sheid.png"
  },
  {
    "slug": "endless-daily-wellness",
    "name": "ENDLESS",
    "subtitle": "Daily Wellness Support",
    "category": "Daily Nutrition",
    "price": 1999,
    "mrp": 1999,
    "countInStock": 25,
    "rating": 4.9,
    "numReviews": 18,
    "badge": "60 CAPSULES",
    "theme": "gold",
    "featured": true,
    "shortDescription": "Daily wellness and vitality support in a convenient capsule format.",
    "description": "Endless is formulated with high-potency Ayurvedic adaptogens including Ashwagandha, Pure Shilajit, Shatavari, and Amla. Designed to support daily stamina, physical endurance, stress relief, and holistic vitality for an active, balanced life.",
    "ingredients": [
      "Shuddha Shilajit Extract",
      "Ashwagandha Extract",
      "Safed Musli Extract",
      "Shatavari Extract",
      "Gokshura Extract",
      "Amla / Indian Gooseberry",
      "Kaunch Beej Extract",
      "Piperine"
    ],
    "benefits": [
      "Supports daily stamina, vigor & vitality*",
      "Helps relieve stress & fatigue*",
      "Supports physical endurance & strength*",
      "Rich in natural rejuvenators and adaptogens*",
      "Convenient daily capsule format*"
    ],
    "size": "60 capsules",
    "form": "Capsules",
    "classification": "Ayurvedic Proprietary Medicine",
    "vegetarian": "100% Vegetarian",
    "storage": "Store in a cool, dry and dark place. Keep away from direct sunlight.",
    "usage": "Take 1 capsule twice daily with milk or water after meals, or as directed by a healthcare professional.",
    "disclaimer": "This product is not intended to diagnose, treat, cure or prevent any disease. Do not exceed the recommended dosage. Keep out of reach of children. Consult a qualified healthcare professional if you are pregnant, breastfeeding, have a medical condition, or take medication.",
    "images": [
      "/images/home/Endless.png"
    ],
    "imageStatus": "Concept",
    "availableForPurchase": true,
    "sortOrder": 1,
    "cardImage": "/images/home/Endless.png"
  },
  {
    "slug": "lean-shape-garcinia-cambogia",
    "name": "LEAN SHAPE",
    "subtitle": "Garcinia Cambogia Capsules",
    "category": "Weight Management",
    "price": 2499,
    "mrp": 2499,
    "countInStock": 25,
    "rating": 4.8,
    "numReviews": 21,
    "badge": "60 CAPSULES",
    "theme": "lime",
    "featured": true,
    "shortDescription": "A botanical wellness formula designed to complement mindful nutrition and an active lifestyle.",
    "description": "Lean Shape brings together selected botanical ingredients including standardized Garcinia Cambogia, Green Coffee Bean, Green Tea, and Ginger in a convenient capsule format to support a balanced weight-management routine alongside nutritious food and daily movement.",
    "ingredients": [
      "Garcinia Cambogia Extract (60% HCA)",
      "Green Coffee Bean Extract",
      "Green Tea Extract",
      "Guggul Extract",
      "Piperine / Black Pepper Extract",
      "Chromium Picolinate",
      "L-Carnitine",
      "Ginger Extract"
    ],
    "benefits": [
      "Supports healthy weight management*",
      "Supports natural metabolism & calorie burn*",
      "Helps maintain active energy throughout the day*",
      "Supports digestive wellness and satiety*",
      "Made with selected botanical extracts*"
    ],
    "size": "60 capsules",
    "form": "Capsules",
    "classification": "Ayurvedic Proprietary Medicine",
    "vegetarian": "100% Vegetarian",
    "storage": "Store in a cool, dry and dark place. Keep away from direct sunlight.",
    "usage": "Take 1 capsule twice daily, 30–45 minutes before meals with a glass of water, or as directed by a healthcare professional.",
    "disclaimer": "This product is not intended to diagnose, treat, cure or prevent any disease. Do not exceed the recommended dosage. Keep out of reach of children. Consult a qualified healthcare professional if you are pregnant, breastfeeding, have a medical condition, or take medication.",
    "images": [
      "/images/home/Lean.png",
      "/images/product/WhatsApp Image 2026-09-10 at 1.36.05 PM (1).jpeg",
      "/images/product/WhatsApp Image 2026-09-10 at 1.36.05 PM.jpeg",
      "/images/product/WhatsApp Image 2026-09-10 at 1.36.04 PM (3).jpeg",
      "/images/product/WhatsApp Image 2026-09-10 at 1.36.04 PM (1).jpeg",
      "/images/product/WhatsApp Image 2026-09-10 at 1.36.04 PM.jpeg"
    ],
    "imageStatus": "Concept",
    "availableForPurchase": true,
    "sortOrder": 2,
    "cardImage": "/images/home/Lean.png"
  },
  {
    "slug": "vital-infinity-multivitamin",
    "name": "VITAL INFINITY",
    "subtitle": "Complete Multivitamin Capsules",
    "category": "Daily Nutrition",
    "price": 1999,
    "mrp": 1999,
    "countInStock": 28,
    "rating": 4.9,
    "numReviews": 26,
    "badge": "60 CAPSULES",
    "theme": "amber",
    "featured": true,
    "shortDescription": "A comprehensive daily multivitamin and greens formula created for modern wellness routines.",
    "description": "Vital Infinity combines essential daily vitamins, minerals, and organic botanical extracts like Ashwagandha, Amla, Shatavari, and Shilajit in an easy-to-take capsule format to support overall immunity, daily energy, and holistic well-being.",
    "ingredients": [
      "Organic Ashwagandha",
      "Amla Extract (Natural Vitamin C)",
      "Shatavari Extract",
      "Shilajit Extract",
      "Moringa Leaf Extract",
      "Spirulina",
      "Essential Vitamin Complex",
      "Zinc & Essential Minerals"
    ],
    "benefits": [
      "Comprehensive daily nutritional support*",
      "Supports immune health & antioxidant defense*",
      "Promotes sustained energy & daily vitality*",
      "Supports bone, muscle, and joint health*",
      "Convenient daily multivitamin ritual*"
    ],
    "size": "60 capsules",
    "form": "Capsules",
    "classification": "Ayurvedic Proprietary Medicine",
    "vegetarian": "100% Vegetarian",
    "storage": "Store in a cool, dry and dark place. Keep away from direct sunlight.",
    "usage": "Take 1 capsule daily in the morning with water after breakfast, or as directed by a healthcare professional.",
    "disclaimer": "This product is not intended to diagnose, treat, cure or prevent any disease. Do not exceed the recommended dosage. Keep out of reach of children. Consult a qualified healthcare professional if you are pregnant, breastfeeding, have a medical condition, or take medication.",
    "images": [
      "/images/home/Vital.png"
    ],
    "imageStatus": "Concept",
    "availableForPurchase": true,
    "sortOrder": 3,
    "cardImage": "/images/home/Vital.png"
  }
]
